version: "3.8"
services:
  mongodb-reviews:
    image: 'mongo:7.0'
    environment:
      - MONGO_INITDB_DATABASE=test
    ports:
      - '27017:27017'
    volumes:
      - mongodb-reviews-vol:/data/db
      - ../backends/persistent/:/docker-entrypoint-initdb.d
    networks:
      - book-store-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  backend-reviews:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    environment:
      - MONGODB_HOST=mongodb-reviews
    ports:
      - "3000:3000"
    networks:
      - book-store-network
    depends_on:
      mongodb-reviews:
        condition: service_healthy

volumes:
  mongodb-reviews-vol:

networks:
  book-store-network:
    driver: bridge