services:

  mongodb-reviews:
    environment:
      - MONGO_INITDB_DATABASE=test
    ports:
      - '27017:27017'
    volumes:
      - mongodb-reviews-vol:/data/db
      - ../backends/persistent/:/docker-entrypoint-initdb.d
    image: 'mongo:5.0.5'
    networks:
      - book-store-network


  backend-reviews:
    image: 'chaphe/backend-reviews-image:1.1'
    environment:
      - MONGODB_HOST=mongodb-reviews
    ports:
      - "3000:3000"
    depends_on:
      - mongodb-reviews
    networks:
      - book-store-network

  frontend-reviews:
    image: 'chaphe/frontend-reviews-image:1.0'
    environment:
      - REVIEWS_URL=http://localhost:3000
    ports:
      - "82:80"
    networks:
      - book-store-network
    depends_on:
      - backend-reviews

  mysql-catalog-store:
    image: 'mysql:8.0.27'
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=catalog-library
    ports:
      - '3306:3306'
    volumes:
      - mysql-library-vol:/var/lib/mysql
      - ../backends/persistent/:/docker-entrypoint-initdb.d
    networks:
      - book-store-network

  backend-catalog:
    image: 'chaphe/backend-catalog-image:1.1'
    ports:
      - "8081:8081"
    environment:
      - MYSQL_DB_HOST=mysql-catalog-store
      - MYSQL_DB_PORT=3306
      - MYSQL_DB_USERNAME=root
      - MYSQL_DB_PASSWORD=password
    networks:
      - book-store-network
    depends_on:
      - mysql-catalog-store

  frontend-catalog:
    image: 'chaphe/frontend-catalog-image:1.0'
    ports:
      - "81:80"
    networks:
      - book-store-network
    depends_on:
      - backend-catalog

volumes:
  mysql-library-vol:
    external: false
  mongodb-reviews-vol:
    external: false

networks:
  book-store-network:
    driver: bridge